### ISSUE TITLE
Not able to post selected files.

### ISSUE THREAD

**Issue by XGeohound** [gkShine/jquery-multiselect#2]
Dear gkShine,

would it be possible for you to explain to me quickly how to access and post the selected items from a table?

Thank you very much,

XGeohound

**Comment by gkShine** [comment]
```
$(function () {
    $('#table1').multiSelect({
        actcls: 'info', //selected class
        selector: 'tbody tr', //select item
        except: ['tbody'], //except dom class
        statics: ['.danger', '[data-no="1"]'], // except dom selector
        callback: function (items) { //select callback
            $('#table2').empty().append(items.clone().removeClass('info').addClass('success'));
        }
    });
})
```

**Comment by XGeohound** [comment]
Dear gkShine,

thank you very much for your reply. Unfortunately it is not helping me too much. 

``` javascript
    <script>
  $(function () { // your function to select items is working just fine :)
        $('#table_data_names').multiSelect({
            actcls: 'grp-selected', 
            selector: 'tbody tr', 
            except: ['tbody'], 
            statics: ['.danger', '[data-no="1"]'], 
            callback: function (items) {
               $('#zip_button').show();
            }

        });

  });
</script>
<script>
    function downloadZip(){ //The problem is, I'm want to give the selected items to this function,
                            //in order to download them. But they get not transfered. 
        var result = new Array();       
        $('#table_data_names tr.grp-selected').each(function(index) {           
            if($(this).attr('id') == "filetype") {
                result.push($(this).text());                
            }
        });
        $('#downloadList').val(result);     


        $("#actionForm").submit();
```

Here is the whole code again, but just with original JQuery. Here downloading works just fine, but One-Click Selection does not work and your included Ctrl-A neither. That's why I'd love to do the job with your awesome script. Do you need any further information?

``` javascript
 $(function() {
    $('#zip_button').hide();
    $( "#table_data_names" ).selectable({
        distance: 1,
        stop: function( event, ui ) {
            $( "#table_data_names td.ui-selected" ).siblings().addClass("ui-selected");
            $('#zip_button').show();
        }
    });

    function downloadZip(){     
        var result = new Array();       
        $('#table_data_names td-ui-selected').each(function(index) {            
            if($(this).attr('id') == "filetype") {
                result.push($(this).text());                
            }
        });
        $('#downloadList').val(result);     


        $("#actionForm").submit();
    }
```

//notice that here I'm using firstly td instead of tr and secondly the class uji-selected. I have no Idea why I have to change those in order to get your script working.

Please help,

XGeohound

**Comment by gkShine** [comment]
Are you Chinese?

**Comment by XGeohound** [comment]
Errr... I like to describle myself as a citizen of the world, but was born and raised in Germany. Why are you asking?

**Comment by XGeohound** [comment]
Actually I'm not quite sure what my origin has to do with my question..
Have you any ideas, what might cause the problem?

**Comment by gkShine** [comment]
I do not understand what your code want to do.
Can you explain it more detail?
If can be in Chinese, it is better.

**Comment by XGeohound** [comment]
Okay, lemme explain it a lil bit better. Basically I'm currently working on an online DataExplorer, which displays the data on the server. I just wanted to add a downloadbutton, in order to be able to download all the files, the user has selected. The downloading does the downloadZip()-Function. You can see, how I transfer the files with just plain JQuery. The tds get the class td-ui-selected and if they have a filetype attribute (in conclusion they are files), they get submitted

Thank you :)

**Comment by gkShine** [comment]
I think <tr> maybe have no id, so the array is empty

``` js
        $('#table_data_names tr.grp-selected').each(function(index) {           
            if($(this).attr('id') == "filetype") {
                result.push($(this).text());                
            }
        });
```
